version: '3.3'
services:
  comwork_cloud_api:
    restart: always
    image: cwcloud-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api
    env_file:
      - .env
  comwork_cloud_consumer:
    restart: always
    image: cwcloud-consumer:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: consumer
    env_file:
      - .env
  comwork_cloud_scheduler:
    restart: always
    image: cwcloud-scheduler:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: scheduler
    env_file:
      - .env
  comwork_cloud_tests:
    image: cwcloud-tests:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: unit_tests
    volumes:
      - ./cloud_environments_prod.yml:/app/cloud_environments.yml
    env_file:
      - .env
  comwork_cloud_linter:
    image: cwcloud-linter:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: linter
    env_file:
      - .env

