version: '3.8'
services:
  comwork_cloud_api:
    restart: always
    image: cwcloud-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api
  comwork_cloud_consumer:
    restart: always
    image: cwcloud-consumer:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: consumer
  comwork_cloud_scheduler:
    restart: always
    image: cwcloud-scheduler:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: scheduler
  comwork_cloud_tests:
    image: cwcloud-tests:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: unit_tests
    volumes:
      - ./cloud_environments_prod.yml:/app/cloud_environments.yml
  comwork_cloud_linter:
    image: cwcloud-linter:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: linter
  comwork_cloud_bandit:
    image: cwcloud-bandit:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: code_scanner
    volumes:
      - .:/app

