global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'cwcloud'
    static_configs:
      - targets: ['comwork_cloud_api:5000']
  - job_name: 'opentelemetry'
    static_configs:
      - targets: ['comwork_cloud_otel_collector:8889']
